# The include statements pull in functionality that automatically detects the machine’s architecture
# and uses the correct compiler and linker.
include $(GOROOT)/src/Make.inc
TARG=pack1
GOFILES=\
pack1.go\
pack1b.go\
include $(GOROOT)/src/Make.pkg

# executable with chmod 777 ./Makefile.